---


- hosts: localhost
  connection: local
  become: yes

  tasks:
    - apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        state: present

    - apt_repository:
        repo: deb https://download.sublimetext.com/ apt/stable/
        state: present

    - name: Sublime Text 3
      apt:
        name: sublime-text
        state: present
        update_cache: true


    - apt_repository:
        repo: ppa:dobey/redshift-daily

    - name: Install redshift
      apt:
        name: redshift
        update_cache: true


    - apt_repository:
        repo: deb http://dl.google.com/linux/chrome/deb/ stable main
        state: present
        filename: google-chrome

    - name: Install numlockx package to have Numlock always enabled by i3wm
      apt:
        name: numlockx
        state: present
        update_cache: true


